### PR TITLE
Update to 1.19.2

### PR DESCRIPTION
**Pull request by solonovamax**
Update to 1.19.2, as there were some changes that break it

### CODE REVIEW

**Comment by solonovamax** [comment]
Also, do you think you could add the `hacktoberfest` topic to the repo?

**Comment by ghost** [comment]
Hello @solonovamax, thank you so much for this port. I was already looking for it 😍

**Comment by solonovamax** [comment]
I ported this like a month ago but forgot to pr until now lol

**Comment by ghost** [comment]
I was checking from time to time the Discord and was even asking for 1.19.2 port. But it seems that Giggotbyte is currently busy 😪
But it's great that I can use it now 😊

**Comment by solonovamax** [comment]
> I was checking from time to time the Discord and was even asking for 1.19.2 port.

I'm not in the discord so I'd never have seen that lol. But, it wasn't a super difficult port, so if you know some basic modding you could've done it yourself. I did it in maybe 10-15 minutes tops

**Comment by Giggitybyte** [comment]
Looks good! Thank you for taking the time.
Apologies for not acknowledging this sooner; I managed to miss any notification of this PR!

**Pull request merged**
